# Generated by Django 2.2.16 on 2024-02-08 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Введите заголовок', verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Введите текст', verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время публикации')),
                ('group', models.CharField(choices=[('Персонажи', 'Персонажи'), ('Локации', 'Локации'), ('Оружие', 'Оружие'), ('Миссии', 'Миссии'), ('Противники', 'Противники')], help_text='Выберите раздел', max_length=150, verbose_name='Раздел')),
                ('image', models.ImageField(blank=True, help_text='Прикрепите картинку', upload_to='images/', verbose_name='Картинка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-pub_date',),
            },
        ),
    ]
