# Generated by Django 2.2.16 on 2024-02-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.CharField(choices=[('persons', 'Персонажи'), ('locations', 'Локации'), ('weapon', 'Оружие'), ('missions', 'Миссии'), ('enemies', 'Противники')], help_text='Выберите раздел', max_length=150, verbose_name='Раздел'),
        ),
    ]
