# Generated by Django 3.2.24 on 2024-02-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240208_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите Имя', max_length=100, verbose_name='Имя')),
                ('text', models.TextField(help_text='Введите Имя', verbose_name='Имя')),
                ('email', models.EmailField(help_text='Введите почту', max_length=254, verbose_name='Почта')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время отправки')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
