# Generated by Django 3.2.24 on 2024-02-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240214_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-date',), 'verbose_name': 'Письмо от пользователя', 'verbose_name_plural': 'Письма от пользователей'},
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
